### ISSUE TITLE
download link is outdated

### ISSUE THREAD

**Issue by GitHub-Crow** [Jake-WU/Det-Fly#1]
Link in readme has outdated, could you update it? Thansk for your time : ) .

**Comment by zhysee** [comment]
Hello, the links have been updated, and you can download the dataset now.

**Comment by Jake-WU** [comment]
> Link in readme has outdated, could you update it? Thansk for your time : ) .

Hello, the links have been updated, and you can download the dataset now.

**Comment by Nr-rN** [comment]
hi, that dataset can't be completely downloaded use office 365 download method, could you provide a new download method or compressed package? thanks.

**Comment by Jake-WU** [comment]
> hi, that dataset can't be completely downloaded use office 365 download method, could you provide a new download method or compressed package? thanks.

Hi, we have tested many times that the dataset can be downloaded successfully. I guess your network is not stable and maybe you can try it again by closing other downloading items.
